### ISSUE TITLE
Join Forces? 

### ISSUE THREAD

**Issue by rylanharper** [konkonam/nuxt-shopify#5]
Hey there! I was exploring this module recently and really like how you’re implementing the Storefront API here—great work!

I just made [Nitrogen](https://github.com/rylanharper/Nitrogen) public a couple of days ago. It’s a minimal rebuild of Shopify Hydrogen in a Nuxt4 environment, covering all core Storefront API features, including advanced aspects like customer accounts, localization, and collection/search filters. I’m also adding the final Shopify-based components next week (product recommendations, product details, etc.). I opted not to make it a module, focusing instead on the flexibility of having open queries and metafields within the API.

I was curious about your approach to API integration here—do you feel it might offer an advantage over my current setup? I like the codegen integration hook in this module; I’m using a manual setup that leverages the same config as Hydrogen (but a hook would be nice lol).

I'd love to explore ways we might collaborate! One key area I’m still working through is integrating Shopify analytics, which seems complex for a headless setup outside of Hydrogen. Have you considered adding support for this in your module?

Cheers 🍻

**Comment by konkonam** [comment]
Hey! We checked out your implementation and are really impressed with what you’ve done! We think your project and ours would go great together.

We were working on a Shopify shop for a friend, and if we had seen your project earlier, we probably would have just used it instead. 😁

So, our plan now is to create a fully typed implementation of Shopify API’s with minimal configuration overhead. Originally, we also planned to provide some usage examples in the playground, but with your project, we could even guide users to a proper and thorough implementation. Right now, we’re still focusing on getting the module up and running properly, and we’re planning to release it on npm soon.

Now, about your questions…

- About our API implementation: We focused on the clients Shopify provides because they automatically integrate the generated types and take care of all the additional steps that are needed.
- And Analytics: We haven’t looked into this yet, but we’ll probably need it too. Maybe we could be of help, for example with European GDPR compliance since we’re based in Germany.

So, if you’d like, we could take care of the “low-level” API/type stuff and point to your repository for a full implementation.

You can reach out to us on Discord:
- konko
- freb97

Cheers! 🍻

**Comment by rylanharper** [comment]
Appreciate the quick reply!

This sounds awesome—I’ll keep an eye on the project/module. If it can be integrated smoothly, I’d love to use it to replace my current `/server/api` setup in Nitrogen. I'm thinking it could allow me to consolidate my GraphQL queries, client, and operations into a shared folder, though I’m not sure how well that would work. The main priority would be achieving a clear separation of concerns: using the module as a connection proxy while keeping query and mutation customization open, since every store has its own unique needs.

For Shopify analytics, I’m considering a custom composable/wrapper similar to [Hydrogen’s](https://github.com/Shopify/hydrogen/blob/2a978cd213608ed47938fab8f3695cbf869b371d/packages/hydrogen/src/analytics-manager/ShopifyAnalytics.tsx), though that might be a long-term implementation for me. In the short term, I'm focusing on the final Shopify storefront components and testing some edge cases (the project is still a WIP but quite stable). I’m also meeting with a developer this week who may help with the analytics part, so we’ll see how that goes.

Again, great start to this module. I'll stay in touch via Discord!

**Comment by rylanharper** [comment]
Closing issue - will be available to chat via Discord!
